services:
  db:
    image: postgres:15-alpine
    container_name: chronos_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: chronos
    ports:
      - "5432:5432"
    volumes:
      - chronos_data:/var/lib/postgresql/data

volumes:
  chronos_data:
